server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/qocksdlf123/richminime-msa"
          clone-on-start: true
          default-label: main
          search-paths: back/src/main/resources